services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=upstash_password_here
      - REDIS_PASSWORD=upstash_password_here
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
